# name: Client Start

# on:
#   push:
#     branches: [main, feDev] 

# jobs:
#   build:
#     runs-on: ubuntu-latest 

#     steps:
#       - name: Checkout source code.
#         uses: actions/checkout@v3

#       - name: Install dependencies
#         run: npm install --force
#         working-directory: ./ecoders-front

#       - name: Check Node v
#         run: node -v
#         working-directory: ./ecoders-front

#       - name: Build
#         run: CI=false npm run build
#         working-directory: ./ecoders-front

#       - name: Deploy (Upload Build File To S3)
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           aws s3 cp --recursive --region ap-northeast-2 build s3://polareco-deploy
#         working-directory: ./ecoders-front
